services:
  notify-bot:
    build: .
    volumes:
      - ${PWD}/config.json:/app/config.json
      - ${PWD}/data:/app/data
    user: "1000:1000"
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
