services:
  mongo:
    image: mongo:8
    restart: always
    volumes:
      - ${PWD}/mongo:/data/db
  notify-bot:
    restart: always
    build: .
    volumes:
      - ${PWD}/config.json:/config.json
    depends_on:
      - mongo
